cambios en fichero de integrations

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -7,16 +7,48 @@ on:
 jobs:
   integrate:
     runs-on: ubuntu-latest
+
+    permissions:
+      contents: read
+      pull-requests: write
+
     steps:
-      - uses: actions/checkout@v3
+      - name: Checkout code
+        uses: actions/checkout@v3
+    
       - name: Set up Python
-        uses: actions/setup-python@v4
+        uses: actions/setup-python@v5
         with:
           python-version: '3.11'
+
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
+        continue-on-error: true
+
       - name: Run tests
+        id: test
         run: |
-          pytest tests/
+        mkdir -p tests_results
+        PYTHONPATH=src pytest unit_tests/ --capture=tee-sys --cov=model --cov=evaluate --cov=data_loader --cov-report=term --cov-report=html --junitxml=test-results/results.xml > test-results/results.log
+        
+      - name: Comnentar resultados en PR
+        uses: actions/github-script@v7
+        with:
+          script: |
+            const fs = require('fs');
+            const results = fs.readFileSync('test-results/results.log', 'utf8');
+            const truncated = results.length > 65000 ? results.slice(0, 65000) + '\n...TRUNCATED...' : results;
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: `### 🧪 Test Results with Coverage\n\n\`\`\`\n${truncated}\n\`\`\``
+            });
+
+      - name: Fallo en caso de no pasar unit tests
+        if: steps.test.outcome == 'failure'
+        run: |
+          echo "Unit tests failed. See the test results above for details."
+          exit 1       
